### PR TITLE
Fix link error

### LINKED ISSUE #27: Deadlink in benchmark/tool/C
https://github.com/PaddlePaddle/Mobile/tree/develop/benchmark/tool/C

> Refer to this document to compile the Android version of PaddlePaddle

The link to `this document` is a dead link. What does the `PADDLE_ROOT` mean in the cmake arguments? 

```bash
cmake .. \
-DANDROID_ABI=arm64-v8a \
-DANDROID_STANDALONE_TOOLCHAIN=your/path/to/arm64_standalone_toolchain \
-DPADDLE_ROOT=The output path generated in the first step \
-DCMAKE_BUILD_TYPE=MinSizeRel
```

### PR DESCRIPTION
**Pull request by hedaoyuan**
Fix #27

### CODE REVIEW

File: benchmark/tool/C/inference.cc [hunk 1]
```diff
@@ -76,8 +76,7 @@ int main(int argc, char* argv[]) {
 
   {
     Timer time("init paddle");
-    char* argv[] = {(char*)"--use_gpu=False"};
-    if (paddle_init(1, (char**)argv) != kPD_NO_ERROR) {
+    if (paddle_init(0, NULL) != kPD_NO_ERROR) {
```
Comment (hedaoyuan) [inline benchmark/tool/C/inference.cc:79]: In mobile inference library, the default value of `use_gpu` is false.
And some people have some doubts about the way this input parameter, so remove the `argv` in the demo.

**Review by qingqing01 — APPROVED** [review]
LGTM.
